// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Storage.Data;

namespace Storage.Migrations
{
    [DbContext(typeof(StorageContext))]
    [Migration("20210307131403_DataAttribute")]
    partial class DataAttribute
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Storage.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("Orderdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Shelf")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Mobile",
                            Count = 156,
                            Description = "Stupid",
                            Name = "Iphone",
                            Orderdate = new DateTime(2021, 3, 1, 14, 14, 3, 144, DateTimeKind.Local).AddTicks(5014),
                            Price = 15600,
                            Shelf = "4B"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Mobile",
                            Count = 98,
                            Description = "Better",
                            Name = "S10",
                            Orderdate = new DateTime(2021, 2, 12, 14, 14, 3, 146, DateTimeKind.Local).AddTicks(139),
                            Price = 12450,
                            Shelf = "4C"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Computers",
                            Count = 23,
                            Description = "Stupid",
                            Name = "MacBook",
                            Orderdate = new DateTime(2021, 3, 2, 14, 14, 3, 146, DateTimeKind.Local).AddTicks(159),
                            Price = 45600,
                            Shelf = "4C"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Computer",
                            Count = 32,
                            Description = "Stupid",
                            Name = "Surface X",
                            Orderdate = new DateTime(2021, 1, 26, 14, 14, 3, 146, DateTimeKind.Local).AddTicks(163),
                            Price = 26850,
                            Shelf = "5C"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Office Supplies",
                            Count = 15651,
                            Description = "Stupid",
                            Name = "Pen",
                            Orderdate = new DateTime(2021, 3, 1, 14, 14, 3, 146, DateTimeKind.Local).AddTicks(166),
                            Price = 1,
                            Shelf = "45W"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
